### ISSUE TITLE
when click dedicate button,nothing happened,no spawner was created

### ISSUE THREAD

**Issue by sduerpang** [insthync/ShooterIOMasterServer#4]
it works fine when in the editor ,clicking start button and two spawner processes will show up, but after building it  with name "Build.exe",when i click dedicate button and nothing happened,i can figure it out, can you help me ? thanks .

**Comment by insthync** [comment]
It might be because build exe path is incorrect, in editor and build are different, I recommend to make shortcut then change build path at `Target` field for example `-msfExe "C:\Game\Game.exe"` you may see about shortcut in https://medium.com/suriyun-production/battle-io-master-server-integration-1b947ad51154 at Running in production section

**Comment by sduerpang** [comment]
it seems that it will work when add argument -msfStartMaster -msfStartSpawner,anyway,thanks a lot

**Comment by sduerpang** [comment]
it seems that it will work when add argument -msfStartMaster -msfStartSpawner,anyway,thanks a lot
